spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

management:
  server:
    port: 5252
  endpoints:
    web:
      base-path: /
      exposure:
        include: logfile
  endpoint:
    logfile:
      external-file: logs/reviewme.log

logging:
  config: classpath:logback-spring.xml
  file:
    path: logs
    name: reviewme.log
  level:
    springframework: DEBUG
  logback:
    rolling-policy:
      max-history: 100
      file-name-pattern: reviewme.%d{yyyy-MM-dd}.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
