spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

management:
  server:
    port: 5252
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, loggers, logfile

logging:
  file:
    path: log
  level:
    root: debug
  logback:
    rolling-policy:
      file-name-pattern: /log/%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      max-history: 100
